name: simple-einet
channels:
  - defaults
dependencies:
  - appnope=0.1.2=py39hca03da5_1001
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - brotli=1.0.7=hc377ac9_0
  - ca-certificates=2022.4.26=hca03da5_0
  - certifi=2021.10.8=py39hca03da5_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h1192e45_0
  - giflib=5.2.1=h1a28f6b_0
  - ipython=8.3.0=py39hca03da5_0
  - jedi=0.18.1=py39hca03da5_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h1a28f6b_0
  - kiwisolver=1.3.2=py39hc377ac9_0
  - lcms2=2.12=hba8e193_0
  - libcxx=12.0.0=hf6beb65_1
  - libffi=3.4.2=hc377ac9_2
  - libgfortran=5.0.0=11_1_0_h6a59814_26
  - libgfortran5=11.1.0=h6a59814_26
  - libopenblas=0.3.18=hea475bc_0
  - libpng=1.6.37=hb8d0fd4_0
  - libtiff=4.2.0=h11e2f9f_0
  - libwebp=1.2.2=h68602c7_0
  - libwebp-base=1.2.2=h1a28f6b_0
  - llvm-openmp=12.0.0=haf9daa7_1
  - lz4-c=1.9.3=hc377ac9_0
  - matplotlib=3.5.1=py39hca03da5_1
  - matplotlib-base=3.5.1=py39hc377ac9_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - munkres=1.1.4=py_0
  - ncurses=6.3=h1a28f6b_2
  - openssl=1.1.1n=h1a28f6b_0
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py39hca03da5_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.9.11=hbdb9e5c_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - readline=8.1.2=h1a28f6b_1
  - scikit-learn=1.0.2=py39h9197a36_1
  - setuptools=58.0.4=py39hca03da5_1
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=h1058600_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.11=hb8d0fd4_0
  - tornado=6.1=py39h1a28f6b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - tzdata=2022a=hda174b7_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1a28f6b_0
  - zlib=1.2.11=h5a0b063_4
  - zstd=1.4.9=h8574219_1
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - argparse==1.4.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - blessings==1.7
    - cachetools==5.0.0
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - clean-fid==0.1.23
    - click==8.1.3
    - colorama==0.4.4
    - commonmark==0.9.1
    - docker-pycreds==0.4.0
    - fancycompleter==0.9.1
    - fast-pytorch-kmeans==0.1.6
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.4
    - google-auth-oauthlib==0.4.6
    - gpustat==0.6.0
    - grpcio==1.44.0
    - icecream==2.1.2
    - idna==2.10
    - importlib-metadata==4.11.3
    - markdown==3.3.6
    - multidict==6.0.2
    - nodeenv==1.6.0
    - numpy==1.22.3
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.0
    - pandas==1.4.2
    - pathtools==0.1.2
    - pdbpp==0.10.3
    - pillow==8.4.0
    - promise==2.3
    - protobuf==3.20.0
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pynvml==11.4.1
    - pyrepl==0.9.0
    - pyright==1.1.244
    - pytorch-lightning==1.6.1
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.25.1
    - requests-oauthlib==1.3.1
    - rich==10.16.2
    - rsa==4.8
    - rtpt==0.0.4
    - scipy==1.8.0
    - seaborn==0.11.2
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - sklearn==0.0
    - smmap==5.0.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - torch==1.11.0
    - torchmetrics==0.8.0
    - torchvision==0.12.0
    - tqdm==4.62.3
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - wandb==0.12.17
    - werkzeug==2.1.1
    - wmctrl==0.4
    - yarl==1.7.2
    - zipp==3.8.0
prefix: /Users/steven/.conda/envs/simple-einet
